/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import datos.Cliente;
import lista.ListaSimpleEncadenada;

/**
 *
 * @author Usuario
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    
    private ListaSimpleEncadenada <Cliente> lista;
    
    
    
    public VentanaPrincipal() {
        initComponents();
        this.lista = new ListaSimpleEncadenada<Cliente>();
    }
    
    
    public void accionesListado(){
        VentanaListado vl = new VentanaListado();
        vl.agregarPuntero(this.lista);
        vl.listarElementos();
        vl.setVisible(true);
    }
    
    public void accionesAltas(){
        Altas v = new Altas();
        v.agregarPuntero(this.lista);
        v.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAltas = new javax.swing.JButton();
        jButtonListado = new javax.swing.JButton();
        jButtonListado1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCliente = new javax.swing.JMenu();
        jMenuItemAltaCliente = new javax.swing.JMenuItem();
        jMenuItemModificarCliente = new javax.swing.JMenuItem();
        jMenuItemBajasCliente = new javax.swing.JMenuItem();
        jMenuItemListadoCliente = new javax.swing.JMenuItem();
        jMenuAyuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Taller de Interfaz Grafica en Java");

        jButtonAltas.setText("Agregar Cliente");
        jButtonAltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltasActionPerformed(evt);
            }
        });

        jButtonListado.setText("Listar Clientes");
        jButtonListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListadoActionPerformed(evt);
            }
        });

        jButtonListado1.setText("Modificar Clientes");
        jButtonListado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListado1ActionPerformed(evt);
            }
        });

        jMenuCliente.setText("Clientes");
        jMenuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuClienteActionPerformed(evt);
            }
        });

        jMenuItemAltaCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemAltaCliente.setText("Agregar Cliente");
        jMenuItemAltaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAltaClienteActionPerformed(evt);
            }
        });
        jMenuCliente.add(jMenuItemAltaCliente);

        jMenuItemModificarCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemModificarCliente.setText("Modificar Cliente");
        jMenuCliente.add(jMenuItemModificarCliente);

        jMenuItemBajasCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemBajasCliente.setText("Eliminar Cliente");
        jMenuItemBajasCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBajasClienteActionPerformed(evt);
            }
        });
        jMenuCliente.add(jMenuItemBajasCliente);

        jMenuItemListadoCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemListadoCliente.setText("Listar Clientes");
        jMenuItemListadoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListadoClienteActionPerformed(evt);
            }
        });
        jMenuCliente.add(jMenuItemListadoCliente);

        jMenuBar1.add(jMenuCliente);

        jMenuAyuda.setText("Ayuda");
        jMenuBar1.add(jMenuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jButtonAltas)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonListado1)
                    .addComponent(jButtonListado))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAltas)
                    .addComponent(jButtonListado))
                .addGap(28, 28, 28)
                .addComponent(jButtonListado1)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListadoActionPerformed
        // TODO add your handling code here:
        accionesListado();
    }//GEN-LAST:event_jButtonListadoActionPerformed

    private void jButtonAltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltasActionPerformed
        // TODO add your handling code here:
        accionesAltas();
    }//GEN-LAST:event_jButtonAltasActionPerformed

    private void jMenuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuClienteActionPerformed

    private void jMenuItemListadoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListadoClienteActionPerformed
        // TODO add your handling code here:
        accionesListado();
    }//GEN-LAST:event_jMenuItemListadoClienteActionPerformed

    private void jMenuItemAltaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAltaClienteActionPerformed
        // TODO add your handling code here:
        accionesAltas();
    }//GEN-LAST:event_jMenuItemAltaClienteActionPerformed

    private void jMenuItemBajasClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBajasClienteActionPerformed
        // TODO add your handling code here:
        VentanaBajas vb = new VentanaBajas();
        vb.agregarPuntero(lista);
        vb.setVisible(true);
    }//GEN-LAST:event_jMenuItemBajasClienteActionPerformed

    private void jButtonListado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListado1ActionPerformed
        Modificaciones vb = new Modificaciones();
        vb.agregarPuntero(lista);
        vb.setVisible(true);
    }//GEN-LAST:event_jButtonListado1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAltas;
    private javax.swing.JButton jButtonListado;
    private javax.swing.JButton jButtonListado1;
    private javax.swing.JMenu jMenuAyuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCliente;
    private javax.swing.JMenuItem jMenuItemAltaCliente;
    private javax.swing.JMenuItem jMenuItemBajasCliente;
    private javax.swing.JMenuItem jMenuItemListadoCliente;
    private javax.swing.JMenuItem jMenuItemModificarCliente;
    // End of variables declaration//GEN-END:variables
}
